# Generated by Django 5.1.4 on 2024-12-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='folower',
            new_name='followers',
        ),
    ]
